### ISSUE TITLE
updateBrokerage interface cannot use base58 encoded addresses

### ISSUE THREAD

**Issue by zyumingfit** [tronprotocol/protocol#110]
`curl -X POST  https://api.trongrid.io/wallet/updateBrokerage -d '{"owner_address":"TGj1Ej1qRzL9feLTLhjwgxXF4Ct6GTWg2U", "brokerage":20, "visible":true}'`

The above command gives an error， owner_address is encoded in hex format, no error is reported.

**Comment by kevinLee2015** [comment]
Hi, 
Thanks for your report. We will fix it asap.

**Comment by shydesky** [comment]
This problem has been fixed in https://github.com/tronprotocol/java-tron/pull/2766 and released in Odyssey-3.6.6  
thanks for your issue, good job.
