### ISSUE TITLE
./install-googleapis.sh is not valid

### ISSUE THREAD

**Issue by neshala** [tronprotocol/protocol#142]
Content of file ./install-googleapis.sh seems to be outdated and I see two problems there:

cannot find package "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger"
(this package seems to be deprecated and replaced)

And 

`wget http://central.maven.org/maven2/com/google/api/grpc/googleapis-common-protos/0.0.3/googleapis-common-protos-0.0.3.jar`

returns 

--2020-12-24 19:02:17--  http://central.maven.org/maven2/com/google/api/grpc/googleapis-common-protos/0.0.3/googleapis-common-protos-0.0.3.jar
Resolving central.maven.org (central.maven.org)... failed: nodename nor servname provided, or not known.
wget: unable to resolve host address ‘central.maven.org

Can we have this fixed ?

**Comment by donnol** [comment]
Anything update?

**Comment by forfreeday** [comment]
Already solved this problem in the `install-googleapis.sh`
