### ISSUE TITLE
Protocol md files in root should use syntax-highlighting

### ISSUE THREAD

**Issue by ghost** [tronprotocol/protocol#90]
(see title, and example follows.)
   
# Protobuf protocol

**The protocol of TRON is defined by Google Protobuf and contains a range of layers, from account, block to transfer.**

There are 3 types of account—basic account, asset release account and contract account, and attributes included in each account are name, types, address, balance and related asset.

A basic account is able to apply to be a validation node, which has serval parameters, including extra attributes, public key, URL, voting statistics, history performance, etc.

```protobuf
      enum AccountType {   
         Normal = 0;   
         AssetIssue = 1;   
         Contract = 2;
        }
```

**Comment by kevinLee2015** [comment]
Thanks for your suggestions. We will improve.

**Comment by masiha2021crypto** [comment]
> (see title, and example follows.)
> 
> # Protobuf protocol
> **The protocol of TRON is defined by Google Protobuf and contains a range of layers, from account, block to transfer.**
> 
> There are 3 types of account—basic account, asset release account and contract account, and attributes included in each account are name, types, address, balance and related asset.
> 
> A basic account is able to apply to be a validation node, which has serval parameters, including extra attributes, public key, URL, voting statistics, history performance, etc.
> 
> ```proto
>       enum AccountType {   
>          Normal = 0;   
>          AssetIssue = 1;   
>          Contract = 2;
>         }
> ```
