### ISSUE TITLE
Missing query of get votelist by address

### ISSUE THREAD

**Issue by CTJaeger** [tronprotocol/protocol#92]
A very important feature is missing here. How can an SR / SRC view its voters without accessing third party vendors? This is important!

**Comment by kevinLee2015** [comment]
https://tronscan.org/#/address/TGj1Ej1qRzL9feLTLhjwgxXF4Ct6GTWg2U/voters

**Comment by andelf** [comment]
Closed for no response.
Feel free to re-open or open-new if you have any other questions.
